import tailwindcss from '@tailwindcss/vite'
import { definePerson } from 'nuxt-schema-org/schema'
import { profile } from './app/data/profile'
import { projects } from './app/data/projects'
import { skillGroups, skillIconNames } from './app/data/skills'
import { projectPaths, projectSitemapEntries } from './shared/utils/routes'

// Build-time values: they are baked into the prerendered HTML (see docs/deployment).
const siteUrl = process.env.NUXT_SITE_URL || 'http://localhost:3000'
const siteEnv = process.env.NUXT_SITE_ENV || 'staging'

export default defineNuxtConfig({
    // Keep before 2026-08-04: newer dates break nitropack 2.13's Cloudflare output (nitro#4527).
    compatibilityDate: '2026-07-15',
    devtools: { enabled: true },

    modules: [
        '@nuxtjs/color-mode',
        '@nuxtjs/i18n',
        '@nuxtjs/seo',
        '@nuxt/fonts',
        '@nuxt/icon',
        '@nuxtjs/turnstile',
    ],

    css: ['~/assets/css/main.css'],
    vite: { plugins: [tailwindcss()] },

    app: {
        viewTransition: true,
        head: {
            link: [{ rel: 'icon', type: 'image/png', href: '/favicon.png' }],
        },
    },

    site: {
        url: siteUrl,
        name: profile.name,
        defaultLocale: 'it',
        env: siteEnv,
        indexable: siteEnv === 'production',
    },

    colorMode: {
        preference: 'system',
        fallback: 'dark',
        classSuffix: '',
        storageKey: 'theme',
    },

    i18n: {
        strategy: 'prefix_except_default',
        defaultLocale: 'it',
        baseUrl: siteUrl,
        customRoutes: 'meta',
        // No redirect on "/": pages are prerendered and each language has its own URL.
        detectBrowserLanguage: false,
        locales: [
            { code: 'it', language: 'it-IT', name: 'Italiano', file: 'it.json' },
            { code: 'en', language: 'en-US', name: 'English', file: 'en.json' },
        ],
    },

    nitro: {
        preset: 'cloudflare_module',
        cloudflare: { deployConfig: true, nodeCompat: true },
        prerender: {
            crawlLinks: true,
            // Writes /en.html instead of /en/index.html, which Cloudflare would 307 to /en/.
            autoSubfolderIndex: false,
            failOnError: true,
            ignore: ['/api'],
            routes: [
                '/',
                '/en',
                '/privacy',
                '/en/privacy',
                ...projects.flatMap((project) => Object.values(projectPaths(project.slug))),
                '/sitemap.xml',
                '/robots.txt',
            ],
        },
    },

    routeRules: {
        '/api/**': { headers: { 'cache-control': 'no-store', 'x-robots-tag': 'noindex' } },
        '/_fonts/**': { headers: { 'cache-control': 'public, max-age=31536000, immutable' } },
        // Generated by scripts/build-images.ts; names aren't hashed, so cache for a week only.
        '/img/**': { headers: { 'cache-control': 'public, max-age=604800' } },
        '/media/**': { headers: { 'cache-control': 'public, max-age=604800' } },
    },

    ogImage: {
        zeroRuntime: true,
    },

    schemaOrg: {
        identity: definePerson({
            name: profile.name,
            jobTitle: profile.jobTitle.en,
            url: siteUrl,
            sameAs: profile.socials.map((social) => social.url),
            address: {
                addressLocality: profile.location.city,
                addressRegion: profile.location.region,
                addressCountry: profile.location.country,
            },
            knowsAbout: skillGroups.flatMap((group) => group.items.map((skill) => skill.label)),
            vatID: `IT${profile.vatNumber}`,
        }),
    },

    // One /sitemap.xml with hreflang alternates instead of a per-language sitemap index.
    sitemap: {
        sitemaps: false,
        zeroRuntime: true,
        urls: projects.flatMap((project) => projectSitemapEntries(project.slug)),
        exclude: ['/api/**'],
    },

    fonts: {
        families: [
            { name: 'JetBrains Mono', provider: 'google', weights: [400, 500, 700], global: true },
            { name: 'Inter', provider: 'google', weights: [400, 500, 600, 700], global: true },
        ],
    },

    // Icons ship in the client bundle only: no icon API in the Worker, no runtime fetches.
    icon: {
        provider: 'none',
        serverBundle: false,
        fallbackToApi: false,
        clientBundle: {
            scan: true,
            icons: [...skillIconNames, ...profile.socials.map((social) => social.icon)],
            sizeLimitKb: 256,
        },
    },

    turnstile: {
        siteKey: process.env.NUXT_PUBLIC_TURNSTILE_SITE_KEY,
    },

    // Private values, set as Worker secrets in production (NUXT_* env vars).
    runtimeConfig: {
        turnstile: { secretKey: '' },
        turnstileHostname: '',
        contact: { email: '', phone: '' },
        resend: {
            apiKey: '',
            from: 'Portfolio <portfolio@ramaj.dev>',
            to: '',
            dryRun: false,
        },
    },
})
